/*******************************************************************************
 * Copyright (c) 2009, 2025 Mountainminds GmbH & Co. KG and Contributors
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *    Original GosuNullSafetyFilter implementation - Oleksandr Kucherenko (kucherenko.alex[at]gmail.com)
 *    Fixed version with improved pattern matching
 *
 *******************************************************************************/
package org.jacoco.core.internal.analysis.filter;

import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.JumpInsnNode;
import org.objectweb.asm.tree.MethodNode;
import org.objectweb.asm.tree.VarInsnNode;

/**
 * Filters out Gosu compiler-generated null-safety checks.
 *
 * <p>
 * Gosu generates null-safety patterns for null-safe navigation and defensive
 * null checks. This filter identifies and excludes these compiler-generated
 * branches from coverage analysis.
 * 
 * <p>
 * This is a fixed version with improved pattern matching that correctly
 * handles the bytecode patterns generated by Gosu compiler.
 */
public final class GosuNullSafetyFilterFixed implements IFilter {

    public void filter(final MethodNode methodNode,
                       final IFilterContext context, final IFilterOutput output) {
        final Matcher matcher = new Matcher();
        for (final AbstractInsnNode i : methodNode.instructions) {
            matcher.match(i, output);
        }
    }

    /**
     * Gosu Language null-safety matcher that verifies 5 different safety patterns
     * generated by Gosu. This version has improved pattern matching logic.
     */
    private static class Matcher extends AbstractMatcher {

        /**
         * Quick match - expected ALOAD, otherwise exit.
         */
        public void match(final AbstractInsnNode start,
                          final IFilterOutput output) {
            // first step of all matches: aload X -> ...
            if (start.getOpcode() != org.objectweb.asm.Opcodes.ALOAD) {
                return;
            }
            cursor = start;
            final VarInsnNode var = (VarInsnNode) start;

            // Try to match Gosu null-safety patterns
            if (matchNullSafeNavigation(var, output)) {
                return;
            }

            if (matchDefensiveNullCheck(var, output)) {
                return;
            }

            if (matchSimplifiedNullSafe(var, output)) {
                return;
            }

            if (matchBooleanNullSafe(var, output)) {
                return;
            }

            if (matchArrayNullSafe(var, output)) {
                return;
            }
        }

        /**
         * Pattern: aload X -> ifnonnull labelA -> aconst_null -> checkcast ->
         * goto labelB -> labelA
         */
        private boolean matchNullSafeNavigation(final VarInsnNode var,
                                                final IFilterOutput output) {
            // Save starting position
            final AbstractInsnNode startInstruction = var;
            
            // Step 1: ifnonnull
            if (!safeNextIs(org.objectweb.asm.Opcodes.IFNONNULL)) {
                return false;
            }
            final JumpInsnNode ifnonnull = (JumpInsnNode) cursor;
            
            // Step 2: aconst_null
            if (!safeNextIs(org.objectweb.asm.Opcodes.ACONST_NULL)) {
                return false;
            }
            
            // Step 3: checkcast
            if (!safeNext()) {
                return false;
            }
            if (cursor.getOpcode() != org.objectweb.asm.Opcodes.CHECKCAST) {
                return false;
            }
            
            // Step 4: goto
            if (!safeNextIs(org.objectweb.asm.Opcodes.GOTO)) {
                return false;
            }
            
            // Pattern matched - ignore the null-safety check
            output.ignore(startInstruction, ifnonnull);
            output.ignore(ifnonnull.label, cursor);
            return true;
        }

        /**
         * Pattern: aload X -> ifnonnull label -> new NPE -> dup -> init ->
         * athrow -> label
         */
        private boolean matchDefensiveNullCheck(final VarInsnNode var,
                                                final IFilterOutput output) {
            // Save starting position
            final AbstractInsnNode startInstruction = var;
            
            // Step 1: ifnonnull
            if (!safeNextIs(org.objectweb.asm.Opcodes.IFNONNULL)) {
                return false;
            }
            final JumpInsnNode ifnonnull = (JumpInsnNode) cursor;
            
            // Step 2: new NPE
            if (!safeNextIsType(org.objectweb.asm.Opcodes.NEW,
                               "java/lang/NullPointerException")) {
                return false;
            }
            
            // Step 3: dup
            if (!safeNextIs(org.objectweb.asm.Opcodes.DUP)) {
                return false;
            }
            
            // Step 4: invokespecial NPE.init
            if (!safeNextIsInvoke(org.objectweb.asm.Opcodes.INVOKESPECIAL,
                                "java/lang/NullPointerException", "<init>", "()V")) {
                return false;
            }
            
            // Step 5: athrow
            if (!safeNextIs(org.objectweb.asm.Opcodes.ATHROW)) {
                return false;
            }
            
            // Pattern matched - ignore the null-safety check
            output.ignore(startInstruction, ifnonnull);
            output.ignore(ifnonnull.label, cursor);
            return true;
        }

        /**
         * Pattern: aload X -> ifnonnull label -> aconst_null -> areturn ->
         * label
         */
        private boolean matchSimplifiedNullSafe(final VarInsnNode var,
                                                final IFilterOutput output) {
            // Save starting position
            final AbstractInsnNode startInstruction = var;
            
            // Step 1: ifnonnull
            if (!safeNextIs(org.objectweb.asm.Opcodes.IFNONNULL)) {
                return false;
            }
            final JumpInsnNode ifnonnull = (JumpInsnNode) cursor;
            
            // Step 2: aconst_null
            if (!safeNextIs(org.objectweb.asm.Opcodes.ACONST_NULL)) {
                return false;
            }
            
            // Step 3: areturn
            if (!safeNextIs(org.objectweb.asm.Opcodes.ARETURN)) {
                return false;
            }
            
            // Pattern matched - ignore the null-safety check
            output.ignore(startInstruction, ifnonnull);
            output.ignore(ifnonnull.label, cursor);
            return true;
        }

        /**
         * Pattern: aload X -> ifnonnull label -> iconst_0/iconst_1 -> goto ->
         * label
         */
        private boolean matchBooleanNullSafe(final VarInsnNode var,
                                             final IFilterOutput output) {
            // Save starting position
            final AbstractInsnNode startInstruction = var;
            
            // Step 1: ifnonnull
            if (!safeNextIs(org.objectweb.asm.Opcodes.IFNONNULL)) {
                return false;
            }
            final JumpInsnNode ifnonnull = (JumpInsnNode) cursor;
            
            // Step 2: iconst_0 or iconst_1
            if (!safeNext()) {
                return false;
            }
            final int op = cursor.getOpcode();
            if (op != org.objectweb.asm.Opcodes.ICONST_0 && op != org.objectweb.asm.Opcodes.ICONST_1) {
                return false;
            }
            
            // Step 3: goto
            if (!safeNextIs(org.objectweb.asm.Opcodes.GOTO)) {
                return false;
            }
            
            // Pattern matched - ignore the null-safety check
            output.ignore(startInstruction, ifnonnull);
            output.ignore(ifnonnull.label, cursor);
            return true;
        }

        /**
         * Pattern: aload X -> ifnonnull label -> iconst_0/anewarray ->
         * [checkcast] -> goto -> label
         */
        private boolean matchArrayNullSafe(final VarInsnNode var,
                                           final IFilterOutput output) {
            // Save starting position
            final AbstractInsnNode startInstruction = var;
            
            // Step 1: ifnonnull
            if (!safeNextIs(org.objectweb.asm.Opcodes.IFNONNULL)) {
                return false;
            }
            final JumpInsnNode ifnonnull = (JumpInsnNode) cursor;
            
            // Step 2: iconst_0 or anewarray
            if (!safeNext()) {
                return false;
            }
            final int op = cursor.getOpcode();
            if (op != org.objectweb.asm.Opcodes.ICONST_0 && op != org.objectweb.asm.Opcodes.ANEWARRAY) {
                return false;
            }
            
            // Step 3: optional checkcast
            if (cursor.getOpcode() == org.objectweb.asm.Opcodes.ANEWARRAY) {
                // Look ahead for optional checkcast
                AbstractInsnNode next = cursor.getNext();
                while (next != null && (next.getType() == AbstractInsnNode.FRAME ||
                                      next.getType() == AbstractInsnNode.LABEL ||
                                      next.getType() == AbstractInsnNode.LINE)) {
                    next = next.getNext();
                }
                if (next != null && next.getOpcode() == org.objectweb.asm.Opcodes.CHECKCAST) {
                    cursor = next;
                }
            }
            
            // Step 4: goto
            if (!safeNextIs(org.objectweb.asm.Opcodes.GOTO)) {
                return false;
            }
            
            // Pattern matched - ignore the null-safety check
            output.ignore(startInstruction, ifnonnull);
            output.ignore(ifnonnull.label, cursor);
            return true;
        }
    }
}